name: Python package

on: [push]

jobs:
  test:
    strategy:
      max-parallel: 6
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
        USE_LEXBOR=1 python setup.py build_ext --inplace --cython
    - name: Test with pytest
      run: |
        USE_LEXBOR=1 pytest
  lint:
    strategy:
      max-parallel: 6
      matrix:
        python-version: [ 3.8, 3.9, "3.10", "3.11" ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
          USE_LEXBOR=1 python setup.py build_ext --inplace --cython
      - name: Lint flake8
        run: flake8 selectolax tests
      - name: Lint Mypy
        run: mypy selectolax tests
